### ISSUE TITLE
Location list

### ISSUE THREAD

**Issue by sinafischer** [sinafischer/capstone-project#1]
## Value statement

As a **user**
I need **a list of learning cards**
so that **I can improve my knowledge about programming**

## Description (Text, Scribble, Wireframe, Design)

- It's a long scrolling list of cards
- A card contains a question and an answer

## Acceptance criteria

- [ ] Cards have to be visually separated
- [ ] Question and answer are simple text in a good readable size
- [ ] Question and answer are both always visible
- [ ] Cards are scrolled vertically

## Tasks

- [ ] Create feature branch
- [ ] Create components (component names go here) in Storybook
- [ ] Write component tests
- [ ] Add components to app (feature implementation with state)
- [ ] Add missing styles
- [ ] Write integration tests w/ Cypress

## Size

small
