### ISSUE TITLE
drag and drop

### ISSUE THREAD

**Issue by sinafischer** [sinafischer/capstone-project#10]
## Value statement

As a **traveler**
I need **to arrange the order of my activities**
so that **I can put them in the chronological order I am going to do them**

## Acceptance criteria

- [ ] With a tab on the item it gets selected and can be dragged out of its position
- [ ] It can be dragged up and down in the list
- [ ] When released it stays at the new position
- [ ] While being dragged the item has another color to show the user which item is moved in the list
- [ ] The new order is saved in local storage

## Tasks

- [ ] Create feature branch
- [ ] Add component to app (feature implementation with state)
- [ ] Add missing styles

## Size

Choose one of the following: medium
