### ISSUE TITLE
edit function

### ISSUE THREAD

**Issue by sinafischer** [sinafischer/capstone-project#11]
## Value statement

As a **traveler**
I need **to edit my activities**
so that **I can add, remove or change the information**

## Acceptance criteria

- [ ] the editing is done in the form view which is used to add a new activity
- [ ] it has the same validation like the form for a new activity
- [ ] after editing it stays in the same position in the list
- [ ] the changes are stored in local storage

## Tasks

- [ ] Create feature branch
- [ ] Write component tests
- [ ] Add missing styles

## Size

Choose one of the following: medium
