### ISSUE TITLE
photo upload

### ISSUE THREAD

**Issue by sinafischer** [sinafischer/capstone-project#12]
## Value statement

As a **traveler**
I need **to upload pictures**
so that **I have a visual idea of the activity and I can give the visual app appearance a personal flavour**

## Description (Text, Scribble, Wireframe, Design)

- to come

## Acceptance criteria

- [ ] The upload can be done while adding (and editing) an activity
- [ ] It is no requirement, 
- [ ] When there is no picture uploaded the item displays no placeholder
- [ ] Several data types can be used (esp. jpg, png)

## Tasks

- [ ] Create feature branch
- [ ] Write component tests
- [ ] Add component to app
- [ ] Add missing styled

## Size

Choose one of the following: medium
