### ISSUE TITLE
delete activities

### ISSUE THREAD

**Issue by sinafischer** [sinafischer/capstone-project#13]
## Value statement

As a **traveler**
I need **to be able to delete activities**
so that **I don't have unnecessary activities in my app**

## Description (Text, Scribble, Wireframe, Design)

- to come

## Acceptance criteria

- [ ] With the click on 'delete' a pop-up opens and asks if the selected activities really should be deleted
- [ ] There are three options 'delete', 'discard' and 'to back-up pool'
- [ ] When clicked on 'delete' on the pop-up, the activity gets deleted
- [ ] 'Back-up pool' saves the selected activities in a seperate list, so they can be put into the list again

## Tasks

- [ ] Create feature branch
- [ ] Write tests
- [ ] Add missing styles

## Size

Choose one of the following: medium
