### ISSUE TITLE
Create trips to group activities accordingly

### ISSUE THREAD

**Issue by sinafischer** [sinafischer/capstone-project#14]
## Value statement

As a **traveler**
I need **to create trips to put my activities in**
so that **I know which activities belong to which trip**

## Description (Text, Scribble, Wireframe, Design)

- to come

## Acceptance criteria

- [ ] form to create a trip
- [ ] input field for name
- [ ] date picker to select the timeframe
- [ ] trips are displayed in a trip list, when trip selected the activity page opens

## Tasks

- [ ] Create feature branch
- [ ] Write component tests
- [ ] Add component to app
- [ ] Add missing styled

## Size

Choose one of the following: medium
