### ISSUE TITLE
Add new activity

### ISSUE THREAD

**Issue by sinafischer** [sinafischer/capstone-project#2]
## Value statement

As a **traveler**
I need **to be able to add activities**
so that **I can adjust the number to my stay's length and improve my vacation planning**

## Description (Text, Scribble, Wireframe, Design)

![capstone-scribble-2](https://user-images.githubusercontent.com/65189127/86324747-50a25980-bc3f-11ea-959a-2051a71f739c.jpg)

## Acceptance criteria

- [ ] Name input is required
- [ ] The new activity will be displayed on top of the list
- [ ] Reset form 
- [ ] Put focus on name input
- [ ] When scrolled the input part is also scrolling off the screen

## Tasks

- [ ] Create feature branch
- [ ] Create components (ActivityForm) in Storybook
- [ ] Write component tests
- [ ] Add missing styles
- [ ] Testing with Cypress

## Size

small
