### ISSUE TITLE
Add bookmark

### ISSUE THREAD

**Issue by sinafischer** [sinafischer/capstone-project#3]
## Value statement

As a **traveler**
I need **to bookmark my favourite activities**
so that **I know which ones to do first and which one I can still pick**

## Description (Text, Scribble, Wireframe, Design)

- A possibility to highlight the favourite activities visually  

## Acceptance criteria

- [ ] Each item shows if it is either marked or not
- [ ] Each item can be marked and unmarked
- [ ] There is an option to show all marked ones, all unmarked and all activities

## Tasks

- [ ] Include toogle for highlighter
- [ ] filter for all marked, all unmarked, all
- [ ] Styling
- [ ] Testing

## Size

small
