### ISSUE TITLE
Add tags and filter for tags

### ISSUE THREAD

**Issue by sinafischer** [sinafischer/capstone-project#4]
## Value statement

As a **traveler**
I need **a possibility to add tags to my activities**
so that **I can group them thematically or via date**

## Description (Text, Scribble, Wireframe, Design)

- To each item tags can be added 
- Tags are included in the input form

## Acceptance criteria

- [ ] A seperate form to create a new activity
- [ ] Add a button on listPage for adding a new activity
- [ ] There is a filter option to type in tags in order to show only the items with the selected tag, if you type in several selectors it will be handled like an &&
- [ ] Add to the existing form an input field for tags
- [ ] Tags are also submitted with the name and details
- [ ] Tags are not required to create a new list item
- [ ] Tags will be displayed underneath the detail teaser

## Tasks

- [ ] Include new input field
- [ ] Display set tags
- [ ] Include filter for tags
- [ ] Styling

## Size

Choose one of the following: small, medium, large
