### ISSUE TITLE
Add local storage

### ISSUE THREAD

**Issue by sinafischer** [sinafischer/capstone-project#5]
## Value statement

As a **traveler**
I need **to save my new activities**
so that **they stay in the list even after closing the app**

## Description (Text, Scribble, Wireframe, Design)

- Local storage is used to save all activities

## Acceptance criteria

- [ ] Existing activities are put into local storage
- [ ] After adding an activity the new activity list overwrites the existing one in local storage
- [ ] Activities in local storage are fetched from local 
- [ ] If there are no activities in local storage a placeholder suggests to add an activity

## Tasks

- [ ]  Create feature branch
- [ ] Create component (Note) in Storybook
- [ ] Write component tests
- [ ] Add component to app (feature implementation with state)
- [ ] Add missing styles
- [ ] Write integration tests w/ Cypress

## Size

Choose one of the following: small
