### ISSUE TITLE
Add react router

### ISSUE THREAD

**Issue by sinafischer** [sinafischer/capstone-project#6]
## Value statement

As a **traveler**
I need **a separate activity list and a separate form to add one**
so that **I have better structured app and overview**

## Description (Text, Scribble, Wireframe, Design)

- Split into one page with activities and one page with input form
- Add button for new activity on activities page
- Add to form a button to activitiesPage

## Acceptance criteria

- [ ] Buttons '+' and '<--' have fixed position and are displayed all the time
- [ ] User stays on form until '<--' button is explicitly clicked

## Tasks

- [ ]  Create feature branch
- [ ] Create component (Button) in Storybook
- [ ] Write component tests
- [ ] Add component to app (feature implementation with state)
- [ ] Add missing styles
- [ ] Write integration tests w/ Cypress

## Size

Choose one of the following: small, medium, large
